baseURL = "http://alkorcloud.online/"
languageCode = "en-us"
title = "Alkor"
theme = "minimal"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Calin Tataru"
    description = "Сервисный центр Алькор"
    githubUsername = "#"
    accent = "green"
    showBorder = true
    backgroundColor = "white"
    font = "-apple-system" #"Raleway"  # should match the name on Google Fonts! -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans, Liberation Sans, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol, Noto Color Emoji
    highlight = true
    copyright = "Сервисный центр Alkor. Все права защищены."
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
    mainSections = ["menus"]



# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:buh@alkorcloud.online"
    name = "fas fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/username/"
    name = "fab fa-github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/username/"
    name = "fab fa-twitter"
    weight = 3

[[menu.icon]]
    url = "https://vk.com/alkorservice"
    name = "fab fa-vk"
    weight = 4
